debug: false
spring:
  profiles: production
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://database.dhss.ices.io:3306/dhss?characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  activemq:
      broker-url: failover:(tcp://activemq.dhss.ices.io:61616)?startupMaxReconnectAttempts=30&maxReconnectAttempts=3
      pool:
        enabled: true
        max-connections: 20
  dhss:
      task:
          desQName: POSEIDON_DEV
          scriptServerName: script-server.l
          basePath: /data/report/adapter/report
          maxNum: 8
banner:
  location: production.txt

  