spring:
  profiles:
    active: 
      - production
  datasource:
    tomcat:
      default-auto-commit: true
      validation-interval: 1000
      validation-query: /* ping */ SELECT 1
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs-millis: 3600000
      min-evictable-idle-time-millis: 600000
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy 
  data:
    rest:
      base-path: /api/v1
      default-page-size: 15
  dao:
    exceptiontranslation:
      enabled: true
  freemarker:
    cache: false
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
dhss:
  one-click-access: 
    interface-type-resource-name: dhss_web_template
    log-storage-path: /var/log/dhss-solution/dhss-one-click-access/
    client-idle-interval: 180000
    needs-proxy: false
    proxy-server-for-telnet:
      login-name: 
      login-password: 
      server-ip: 
      server-port: 22
server:
  context-path: /oca
    