debug: true
spring:
  profiles: development
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/new_dhss?characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  activemq:
      broker-url: failover:(tcp://127.0.0.1:61616)?startupMaxReconnectAttempts=30&maxReconnectAttempts=3 
  dhss:
      task:
          dataFileDir: 
          loadSql: 
          insertCounterDataSql:  
          updateCounterFlagSql: 
          loadSqlHss2Boss:
          SubsHSS2BOSSCOUNT:
banner:
  location: development.txt
