

spring:
  
  profiles:
    active: development
  datasource:
    tomcat:
      default-auto-commit: false
      validation-interval: 1000
      validation-query: SELECT 1
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs-millis: 3600000
      min-evictable-idle-time-millis: 600000
  jpa:
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy #org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: true
  data:
    rest:
      base-path: /api/v1
      default-page-size: 15
  dao:
    exceptiontranslation:
      enabled: true